### ISSUE TITLE
[Front-end] 클라이언트에서 JWT Token에 연장 유무 메세지를 어떻게 사용자에게 보여줄 것인가?

### ISSUE THREAD

**Issue by peacemaker474** [nayeon-hub/smim#160]
1. 아이디와 비밀번호를 입력하여, 로그인을 한다.
   ▪ 서버에서 Access Token과 Refresh Token을 발급한다.
   ▪ Access Token은 Redux Store에 저장하고, Refresh Token은 쿠키에 저장한다.
2. 로그인이 필요한 서비스에 대해서 클라이언트는 서버에 네트워크를 요청할 시 Access Token만을 보내서,
    해당 요청이 정말 사용자가 맞는지 확인을 한다.
3. 만약, Access Token이 만료 시간이 지날 경우, 클라이언트측에서 Refresh Token을 기반으로 서버에 Access Token 재발급 요청을 한다.
   ▪ 이때, 클라이언트 측은 어떤 방식으로 Access Token이 만료되었는지 알려줄 것인가?가 문제가 된다.
   ▪ 로그인과 동시에 setTimeout으로 Access Token의 만료 시간과 같은 시간으로 Access Token 연장 유무의 
     확인 메세지를 띄울 수 있도록 설정한다.
   ▪ 이 때 발생할 수 있는 문제는 중간의 로그아웃을 하였을시, Web APIs에 남아있는 
     Timer 함수가 이미 설정된 시간 뒤에 동작한다는 것이다.
   ▪ 이것을 해결하기 위해서는, clearTimeout을 활용하여야 한다는 점이다.
   ▪ 위와 같이 해결을 한다고 하더라도, 새로고침을 누를 시 timer 자체가 다시 설정됨으로 Access Token의 만료시간과 달라진다.

**Comment by peacemaker474** [comment]
일단 기존에 따로 쿠키 옵션 설정을 안 해준 상태에서 쿠키에 저장했지만, XSS, 세션 하이재킹과 같은 공격을 막기 위해 HttpOnly 설정을 했다. 이 과정에서 서버측 cors 설정과 프론트측 withcredentials 설정을 통해 서버측에서 refreshToken을 가지고 오도록 설정하였다.

**Comment by nayeon-hub** [comment]
위에서 언급한 게시물을 작성하거나 수정하는 중에 토큰 만료가 되는 문제점은 게시물 작성페이지를 들어갔을 때 토큰을 다시 한번 부여하는 방법으로 해결하였다.

**Comment by nayeon-hub** [comment]
Auth component가 App.jsx안에서 완전히 분리되어 있는데 라우트가 변경될 때마다 내부 로직이 잘 실행할 수 있도록 pathname을 useEffect 의존성에 추가하였다.
